
[advanced]
	#Debug mode enabled
	DebugMode = false
	#Display search bar in the center
	CenterSearch = false
	#Set low-memory mode (makes search very slow, but uses less RAM)
	LowMemorySlowSearchEnabled = false
	#How items should be handed to you
	#Allowed Values: INVENTORY, MOUSE_PICKUP
	GiveMode = "MOUSE_PICKUP"
	#Max number of columns shown
	#Range: 4 ~ 100
	MaxColumns = 12
	#Max. recipe gui height
	#Range: > 175
	RecipeGuiHeight = 350

[colors]
	#Color values to search for
	SearchColors = []

[sorting]
	#Sorting order for the ingredient list. Valid stages: [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU, TAG, TOOL_TYPE, WEAPON_DAMAGE, ARMOR, MAX_DURABILITY]
	IngredientSortStages = ["INGREDIENT_TYPE", "ALPHABETICAL"]

[search]
	#Search mode for Mod Names (prefix: @)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ModNameSearchMode = "DISABLED"
	#Search mode for Tooltips (prefix: #)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	TooltipSearchMode = "REQUIRE_PREFIX"
	#Search mode for Tag Names (prefix: $)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	TagSearchMode = "DISABLED"
	#Search mode for Creative Tab Names (prefix: %)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	CreativeTabSearchMode = "DISABLED"
	#Search mode for Colors (prefix: ^)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ColorSearchMode = "DISABLED"
	#Search mode for resources IDs (prefix: &)
	#Allowed Values: ENABLED, REQUIRE_PREFIX, DISABLED
	ResourceIdSearchMode = "DISABLED"
	#Search advanced tooltips (visible with F3+H)
	SearchAdvancedTooltips = false

[modname]
	#Formatting for mod name tooltip
	#Use these formatting keys:
	#black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
	#obfuscated, bold, strikethrough, underline, italic
	ModNameFormat = ""

