#Chance a tumbleweed spawns in a chunk.
spawnChance = 0.5
#Maximum number of tumbleweeds existing per player (technically 17x17 loaded chunks).
maxPerPlayer = 8
enableDrops = true
#Should tumbleweeds damage crops.
damageCrops = false
#Drop items only when destroyed by player (normally also drops on lava and cactus damage, for example).
dropOnlyByPlayer = false
#These items will drop from a tumbleweed upon destroying. The identifier can include an NBT compound. The amount parameter is optional.
#weight item amount
#Example entry: 2 minecraft:arrow{display:{Name:'{"text":"Cool arrow"}'}} 20
drops = ["1 minecraft:bone", "1 minecraft:dead_bush", "1 minecraft:string", "1 minecraft:stick"]
#Blocks in which tumbleweeds can spawn. Only works with non-solid blocks.
#The actual location also requires sky access and a solid block below it.
#<mod>:<block>
spawningBlocks = ["minecraft:dead_bush"]
#If not empty, tumbleweeds spawn ONLY in the specified biomes. Else they appear in all hot, dry biomes.
#Example entry: minecraft:desert
biomeWhitelist = []

