
[VanillaTweaks]

	#New items, blocks VanillaTweaks adds.
	[VanillaTweaks.content]
		#Want to showcase your treasure but item frame doesn't satisfy you?
		enablePedestal = false
		#Want block forms of flint, charcoal and sugar?
		enableStorageBlocks = false
		#Do you want a portable crafting table?
		enablePad = false
		#Want to identity slime chunks in-game?
		enableSlimeBucket = false
		#Want a less effective but throwable TNT?
		enableDynamite = false
		#Cooldown for the dynamite in ticks
		#Range: > 0
		dynamiteCooldown = 20
		#Explosion power for dynamite. TNT has 4, Ender Crystal has 6
		#Range: 0 ~ 10
		dynamiteExplosionPower = 3
		#Want a food which can be obtained with eggs and heals 2.5 hunger?
		enableFriedEgg = true
		#How much do you want the binoculars to zoom? ( 0 = disabled)
		#Range: 0.0 ~ 1.7976931348623157E308
		binocularZoomAmount = 4.0

	#Do you want enchantments?
	[VanillaTweaks.enchanting]
		#Want to smelt things when you mine them?
		enableBlazing = false
		#Want to jump more than a block high with an enchantment?
		enableHops = false
		#Want more speed with an enchantment?
		enableNimble = false
		#Don't want the zombies stealing your items when you are mining?
		enableSiphon = false
		#Want all the experience in the nearby area?
		enableVeteran = false
		#Want more health with an enchant?
		enableVigor = false
		#Don't want to aim but love shooting arrows?
		enableHoming = false

	#Mob Drops
	[VanillaTweaks.loot]
		#No comment
		#Range: 0.0 ~ 10.0
		batLeatherDropChance = 1.0
		#Does a nametag drop when named mob dies?
		namedMobsDropNameTag = true

	#Modification of vanilla_recipes recipes and addition of new recipes regarding vanilla_recipes
	[VanillaTweaks.crafting]
		#Want 8 stairs rather than 4 in stairs recipe?
		betterStairs = false
		#Cobblestone used in stone tools doesn't make sense?
		betterStoneTools = false
		#Wanna craft multiple chests at one go?
		betterChest = false
		#Tired of not having a nametag?
		nametag = false
		#Have wool but need string?
		string = false
		#Want an easier way to craft repeater?
		betterRepeater = false
		#Wanna easier recipe for trapped chest?
		betterTrappedChestRecipe = false

	#Tweaks
	[VanillaTweaks.tweaks]
		#Want a way to clear text in signs?
		enableSignEditing = true
		#Want the fire arrows to set fire on block it landed?
		arrowsSetBlockOnFire = true
		#Want hoe to act like a sickle?
		hoeActsAsSickle = true
		#Want the ability to move spawners with silk touch?
		enableSilkSpawner = false
		#Do you want to neglect fall damage and get water spilled when you fall on a wet sponge?
		squishySponge = true
		#Want to see the no of bees or the honey level of an beehive?
		enableBeehiveTooltips = true
		#Want to shift click item frame to rotate in the reverse direction?
		itemFrameRotateBackwards = true
		#Want to shear nametag of named entities?
		shearOffNameTag = true
		#Want baby zombies to burn by the light of the day?
		babyZombieBurnInDaylight = true
		#Want creeper's to burn in daylight?
		creeperBurnInDaylight = true
		#Want TNT to ignite when next to lava or magma block?
		tntIgnition = false
		#Want an way to swap armor with armor stand?
		enableArmorStandSwapping = true
		#Want command block to appear in redstone tab?
		commandBlockInRedstone = false
		#Want dragon egg to appear in decorations tab?
		dragonEggInDecorations = false
		#Want to disable shift in GUI due to potions?
		disablePotionShift = true

	#Dynamic changes in the world
	[VanillaTweaks.world]
		#Don't want that that pesky lava pockets in nether to kill you?
		disableLavaPocketGen = true
		#Is realistic predator/prey relationships activated?
		realisticRelationship = true
		#Want seeds to auto-plant themselves when broken?
		selfPlanting = true
		#How long a plant should take to despawn (and attempt to plant) Default Minecraft is 6000.
		#Range: > 0
		despawnTime = 6000
		#Percentage chance to plant
		#Range: 0 ~ 100
		chanceToPlant = 100

