
#Please be advised that certain thirst-related options are world-specific and are located in <Path to your world folder>/serverconfig/toughasnails-server.toml.
[general]
	#The threshold at which exhaustion causes a reduction in hydration and the thirst bar.
	#Range: 0.0 ~ 1.7976931348623157E308
	exhaustion_threshold = 8.0

[drink_options]
	#Thirst restored from drinking with hands.
	#Range: 0 ~ 20
	hand_drinking_thirst = 1
	#Hydration restored from drinking with hands.
	#Range: 0.0 ~ 1.7976931348623157E308
	hand_drinking_hydration = 0.1

	#Effects of drinks from Vanilla, Tough As Nails and other mods.
	[[drink_options.drink_entries]]
		location = "minecraft:potion"
		thirst = 2
		hydration = 0.2
		poison_chance = 0.25

	[[drink_options.drink_entries]]
		location = "toughasnails:dirty_water_bottle"
		thirst = 1
		hydration = 0.1
		poison_chance = 0.75

	[[drink_options.drink_entries]]
		location = "toughasnails:dirty_water_canteen"
		thirst = 1
		hydration = 0.1
		poison_chance = 0.75

	[[drink_options.drink_entries]]
		location = "toughasnails:purified_water_bottle"
		thirst = 3
		hydration = 0.3
		poison_chance = 0.0

	[[drink_options.drink_entries]]
		location = "toughasnails:purified_water_canteen"
		thirst = 3
		hydration = 0.3
		poison_chance = 0.0

	[[drink_options.drink_entries]]
		location = "toughasnails:water_canteen"
		thirst = 2
		hydration = 0.2
		poison_chance = 0.25

[biome_options]

	#The types of water found in biomes from Vanilla and other mods.
	[[biome_options.biome_water_entries]]
		location = "minecraft:swamp"
		type = "DIRTY"

	[[biome_options.biome_water_entries]]
		location = "minecraft:swamp_hills"
		type = "DIRTY"

